/* AUTOGENERATED by src/boot/hook/build.sh - do not edit. */
#ifndef HOOK_BLOB_H__
#define HOOK_BLOB_H__

#include <stdint.h>

#define SC64SS_HOOK_ADDRESS (0x807D0000UL)
#define SC64SS_HOOK_DEV (0)
#define SC64SS_HOOK_CFG_OFFSET (0x1B3B0UL)   /* struct hook_cfg inside the blob */
#define SC64SS_HOOK_CFG_MAGIC (0x43464731UL)
#define SC64SS_HOOK_CFG_WORDS (48)

/* cart SDRAM layout shared with the hook (hook.c) */
#define SC64SS_HOOK_STAGING_PI (0x13F60000UL)   /* cart PI address of the hook's staging copy (128 KiB) */
#define SC64SS_FRAME_STASH_PI (0x13E20000UL)   /* cart PI address of the frame stash */
#define SC64SS_FRAME_STASH_LEN (0x140000UL)   /* its size */
#define SC64SS_STATE_SLOT_LEN (0x7C8000UL)   /* stride of a state slot in cart SDRAM */
#define SC64SS_STATE_HDR_OFF (0x0UL)   /* the state header inside a slot / SD file */
#define SC64SS_STATE_THUMB_OFF (0x1000UL)   /* the thumbnail inside a slot / SD file */
#define SC64SS_SD_TABLE_OFF (0x7C7000UL)   /* the SD file's sector table inside a slot (menu-written) */
#define SC64SS_SD_FILE_SECTORS (0x3E30UL)   /* sectors of a normal-mode state file (head + image) */
#define SC64SS_STATE_IMAGE_OFF (0x4000UL)   /* the RAM image inside a slot / SD file */
#define SC64SS_SD_RUNS_MAX (0x40UL)   /* run table capacity */
#define SC64SS_SD_RUNS_MAGIC (0x53445231UL)   /* run table magic 'SDR1' */
#define SC64SS_SLOTS_MAX (0x8UL)   /* slot table capacity */
#define SC64SS_VPAK_PI (0x13FB0000UL)   /* cart PI address of the virtual Controller Pak image (run table after it) */
#define SC64SS_VPAK_LEN (0x8000UL)   /* its size */
#define SC64SS_VPAK_CTL_PI (0x13FB9000UL)   /* borrowed mode: the pak's control block (the menu zeroes it, 'VPK1' first) */
#define SC64SS_MONITOR_PI (0x13FBA000UL)   /* borrowed mode: cart PI address of the monitor (run in place) */
#define SC64SS_MONITOR_LEN (0x4000UL)   /* its reserved size */
#define SC64SS_STASH_PI (0x13FC0000UL)   /* borrowed mode: cart PI address of the stash of the hook's home */
#define SC64SS_STASH_LEN (0x20000UL)   /* its size */
#define SC64SS_CTX_PI (0x13FBE000UL)   /* borrowed mode: a loaded state's CPU context for the monitor */
#define SC64SS_STATE_SLOT_LEN_B (0x810000UL)   /* borrowed mode: stride of a state slot */
#define SC64SS_STATE_IMAGE_LEN_B (0x800000UL)   /* borrowed mode: the RAM image (all 8 MiB) */
#define SC64SS_SD_TABLE_OFF_B (0x80F000UL)   /* borrowed mode: the run table inside a slot */
#define SC64SS_SD_FILE_SECTORS_B (0x4030UL)   /* borrowed mode: sectors of a state file */
#define SC64SS_SHOT_TABLE_PI (0x13F80000UL)   /* the screenshot file's run table */
#define SC64SS_SHOT_HDR_PI (0x13F81000UL)   /* the screenshot file's header block (4 KiB) */
#define SC64SS_SHOT_HDR_SECTORS (0x8UL)   /* the header block's sectors */
#define SC64SS_SHOT_ENTRIES_MAX (0x1FCUL)   /* screenshots the header block can name */
#define SC64SS_SD_MAGIC_SHOT (0x53484354UL)   /* a fresh screenshot file's marker 'SHFR' */
#define SC64SS_HOOK_STAGING_LEN (0x20000UL)

extern const uint32_t sc64ss_hook_blob[];
extern const uint32_t sc64ss_hook_blob_size;

/* borrowed-RAM mode (lowpage.S, monitor.S) */
#define SC64SS_LOWPAGE_0F0_ADDRESS (0x800000F0UL)
extern const uint32_t sc64ss_lowpage_0f0[];
extern const uint32_t sc64ss_lowpage_0f0_words;
#define SC64SS_LOWPAGE_110_ADDRESS (0x80000110UL)
extern const uint32_t sc64ss_lowpage_110[];
extern const uint32_t sc64ss_lowpage_110_words;
#define SC64SS_LOWPAGE_130_ADDRESS (0x80000130UL)
extern const uint32_t sc64ss_lowpage_130[];
extern const uint32_t sc64ss_lowpage_130_words;
#define SC64SS_LOWPAGE_1DC_ADDRESS (0x800001DCUL)
extern const uint32_t sc64ss_lowpage_1dc[];
extern const uint32_t sc64ss_lowpage_1dc_words;
#define SC64SS_LOWPAGE_360_ADDRESS (0x80000360UL)
extern const uint32_t sc64ss_lowpage_360[];
extern const uint32_t sc64ss_lowpage_360_words;
extern const uint32_t sc64ss_monitor_blob[];
extern const uint32_t sc64ss_monitor_blob_size;
extern const uint32_t sc64ss_monitor_hi_patch[];   /* (index, value) pairs: the scratch at 0x2A8 */
extern const uint32_t sc64ss_monitor_hi_patch_pairs;

#endif
